### PR TITLE
feat: fetching model data from db

### PR DESCRIPTION
**Pull request by thereseLYR**
## Changes
- added a GET route for fetching model data from DB
- this is REQUIRED for the [frontend cookie PR](https://github.com/Nyx92/3D-Model-Ecommerce-Frontend/pull/11) to work 

## How to test
- send a GET request to http://localhost:3004/api/model-data/(whatever-number) via Postman

## Known Issues
- does not handle invalid modelId queries (seed data only contains IDs 1 and 2)

## Screenshots (if any)
image
^ example GET request
image
^ expected output

### CODE REVIEW

**Review by staceyng — APPROVED** [review]
can clear some of the console messages otherwise lgtm!

**Comment by staceyng** [comment]
there's some conflicts with main :(

**Comment by thereseLYR** [comment]
We should be able to resolve the merge conflict after PR approval too

**Comment by sundriedtomato12** [comment]
I resolved the conflict. changed your route to "/api/models/:modelId" as well because my get all models data is "/api/models", so just to keep consistent.

**Review by sundriedtomato12 — APPROVED** [review]

**Pull request merged**
